apiVersion: apps/v1
kind: Deployment

metadata:
  name: db-deployment
  namespace: desafio-db

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 10%
  selector:
    matchLabels:
      db: app-db
  template:
    metadata:
      labels:
        db: app-db
    spec:
      containers:
        - name: app-db
          image: postgres:17
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: app-db-secrets
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: app-db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: app-db-data
          persistentVolumeClaim:
            claimName: app-pvc
