apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: app-pvc
  namespace: desafio-db

spec:
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: app-db-pv
