services:
  postgres:
    container_name: k8s-db
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - links

  short_links_api:
    build: .
    container_name: short_links
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - 3333:3000
    depends_on:
      - postgres
    networks:
      - links

networks:
  links:
    driver: bridge
